// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dashboard/usage/v1/usage.proto (package dashboard.usage.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { TimeRange } from "../../../common/v1/time_pb";
import { file_common_v1_time } from "../../../common/v1/time_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dashboard/usage/v1/usage.proto.
 */
export const file_dashboard_usage_v1_usage: GenFile = /*@__PURE__*/
  fileDesc("Ch5kYXNoYm9hcmQvdXNhZ2UvdjEvdXNhZ2UucHJvdG8SEmRhc2hib2FyZC51c2FnZS52MSLgAQoPR2V0VXNhZ2VSZXF1ZXN0EhcKBm9yZ19pZBgBIAEoCUIHukgEcgIQARIjCgVyYW5nZRgCIAEoCzIULmNvbW1vbi52MS5UaW1lUmFuZ2U6jgG6SIoBGocBChNnZXRfdXNhZ2UucmFuZ2VfbWF4EiZyYW5nZSBtdXN0IG5vdCBzcGFuIG1vcmUgdGhhbiA0MDAgZGF5cxpIIWhhcyh0aGlzLnJhbmdlKSB8fCB0aGlzLnJhbmdlLnRvIC0gdGhpcy5yYW5nZS5mcm9tIDw9IGR1cmF0aW9uKCc5NjAwaCcpIlwKCFVzYWdlRGF5EicKA2RheRgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEgoKcHJvamVjdF9pZBgCIAEoCRITCgtldmVudF9jb3VudBgDIAEoAyLtAQoQR2V0VXNhZ2VSZXNwb25zZRITCgt1c2VkX2V2ZW50cxgBIAEoAxIwCgxwZXJpb2Rfc3RhcnQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnBlcmlvZF9lbmQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjUKEXVzYWdlX2NvbXB1dGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIrCgVkYWlseRgFIAMoCzIcLmRhc2hib2FyZC51c2FnZS52MS5Vc2FnZURheTJnCgxVc2FnZVNlcnZpY2USVwoIR2V0VXNhZ2USIy5kYXNoYm9hcmQudXNhZ2UudjEuR2V0VXNhZ2VSZXF1ZXN0GiQuZGFzaGJvYXJkLnVzYWdlLnYxLkdldFVzYWdlUmVzcG9uc2UiAEJFWkNnaXRodWIuY29tL3B1Zy1zaC9wdWcvaW50ZXJuYWwvZ2VuL3Byb3RvL2Rhc2hib2FyZC91c2FnZS92MTt1c2FnZXYxYghlZGl0aW9uc3DoBw", [file_buf_validate_validate, file_common_v1_time, file_google_protobuf_timestamp]);

/**
 * @generated from message dashboard.usage.v1.GetUsageRequest
 */
export type GetUsageRequest = Message<"dashboard.usage.v1.GetUsageRequest"> & {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId: string;

  /**
   * Bounds the daily series only; used_events always covers the current period.
   * Absent means the current period. The bounds snap outwards to whole UTC days,
   * since that is the grain the counts are stored at — asking for half a day
   * returns that day's whole cell. Metered days are pruned after ~13 months, so a
   * longer window simply returns fewer rows than it asked for.
   *
   * @generated from field: common.v1.TimeRange range = 2;
   */
  range?: TimeRange | undefined;
};

/**
 * Describes the message dashboard.usage.v1.GetUsageRequest.
 * Use `create(GetUsageRequestSchema)` to create a new message.
 */
export const GetUsageRequestSchema: GenMessage<GetUsageRequest> = /*@__PURE__*/
  messageDesc(file_dashboard_usage_v1_usage, 0);

/**
 * UsageDay is one metered (project, day) cell. Cells are per project so a client
 * can break the series down or sum it; days with no events have no row.
 *
 * @generated from message dashboard.usage.v1.UsageDay
 */
export type UsageDay = Message<"dashboard.usage.v1.UsageDay"> & {
  /**
   * UTC midnight starting the day the events were recorded.
   *
   * @generated from field: google.protobuf.Timestamp day = 1;
   */
  day?: Timestamp | undefined;

  /**
   * @generated from field: string project_id = 2;
   */
  projectId: string;

  /**
   * @generated from field: int64 event_count = 3;
   */
  eventCount: bigint;
};

/**
 * Describes the message dashboard.usage.v1.UsageDay.
 * Use `create(UsageDaySchema)` to create a new message.
 */
export const UsageDaySchema: GenMessage<UsageDay> = /*@__PURE__*/
  messageDesc(file_dashboard_usage_v1_usage, 1);

/**
 * @generated from message dashboard.usage.v1.GetUsageResponse
 */
export type GetUsageResponse = Message<"dashboard.usage.v1.GetUsageResponse"> & {
  /**
   * Distinct events recorded across all of the org's projects this period.
   * ABSENT whenever usage_computed_at is — never render it as 0.
   *
   * @generated from field: int64 used_events = 1;
   */
  usedEvents: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp period_start = 2;
   */
  periodStart?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp period_end = 3;
   */
  periodEnd?: Timestamp | undefined;

  /**
   * When the meter last ran for this org. ABSENT means it never has — there is no
   * answer at all, which a deployment not running `pug cron usage` must render as
   * "unknown" rather than "0". A period the meter has not reached yet (the 1st of
   * a month, before the first pass) keeps the previous period's stamp.
   *
   * @generated from field: google.protobuf.Timestamp usage_computed_at = 4;
   */
  usageComputedAt?: Timestamp | undefined;

  /**
   * Per-project daily counts over the requested window, oldest first.
   *
   * @generated from field: repeated dashboard.usage.v1.UsageDay daily = 5;
   */
  daily: UsageDay[];
};

/**
 * Describes the message dashboard.usage.v1.GetUsageResponse.
 * Use `create(GetUsageResponseSchema)` to create a new message.
 */
export const GetUsageResponseSchema: GenMessage<GetUsageResponse> = /*@__PURE__*/
  messageDesc(file_dashboard_usage_v1_usage, 2);

/**
 * @generated from service dashboard.usage.v1.UsageService
 */
export const UsageService: GenService<{
  /**
   * Returns how many events the org's projects recorded in the current calendar
   * month, plus the per-project daily series behind it. The numbers come from a
   * scheduled meter whose cadence the deployment sets, so read usage_computed_at
   * for how stale they are rather than assuming one. Both used_events and
   * usage_computed_at are absent if the meter has never run.
   *
   * @generated from rpc dashboard.usage.v1.UsageService.GetUsage
   */
  getUsage: {
    methodKind: "unary";
    input: typeof GetUsageRequestSchema;
    output: typeof GetUsageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dashboard_usage_v1_usage, 0);

