// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file ai/dashboards/v1/assistant.proto (package ai.dashboards.v1, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Dashboard, DashboardTileInput } from "../../../dashboard/dashboards/v1/dashboards_pb";
import { file_dashboard_dashboards_v1_dashboards } from "../../../dashboard/dashboards/v1/dashboards_pb";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file ai/dashboards/v1/assistant.proto.
 */
export const file_ai_dashboards_v1_assistant: GenFile = /*@__PURE__*/
  fileDesc("CiBhaS9kYXNoYm9hcmRzL3YxL2Fzc2lzdGFudC5wcm90bxIQYWkuZGFzaGJvYXJkcy52MSKdAQoLVHVyblJlcXVlc3QSNQoPY29udmVyc2F0aW9uX2lkGAEgASgJQhy6SBlyFxABGIABMhBeW0EtWmEtejAtOV8tXSskEjoKBXN0YXRlGAIgASgLMiMuYWkuZGFzaGJvYXJkcy52MS5Db252ZXJzYXRpb25TdGF0ZUIGukgDyAEBEhsKB21lc3NhZ2UYAyABKAlCCrpIB3IFEAEYkE4iTgoRQ29udmVyc2F0aW9uU3RhdGUSOQoFZHJhZnQYASABKAsyIi5kYXNoYm9hcmQuZGFzaGJvYXJkcy52MS5EYXNoYm9hcmRCBrpIA9gBAyKVAQoHTWVzc2FnZRI4CgRyb2xlGAEgASgOMh4uYWkuZGFzaGJvYXJkcy52MS5NZXNzYWdlLlJvbGVCCrpIB4IBBBABIAASDwoHY29udGVudBgCIAEoCSI/CgRSb2xlEhQKEFJPTEVfVU5TUEVDSUZJRUQQABINCglST0xFX1VTRVIQARISCg5ST0xFX0FTU0lTVEFOVBACInsKDFR1cm5SZXNwb25zZRIOCgR0ZXh0GAEgASgJSAASJgoCb3AYAiABKAsyGC5haS5kYXNoYm9hcmRzLnYxLlRpbGVPcEgAEioKBGRvbmUYAyABKAsyGi5haS5kYXNoYm9hcmRzLnYxLlR1cm5Eb25lSABCBwoFY2h1bmsiNgoIVHVybkRvbmUSKgoGZmFpbGVkGAEgAygLMhouYWkuZGFzaGJvYXJkcy52MS5GYWlsZWRPcCIuCghGYWlsZWRPcBIOCgZpbnRlbnQYASABKAkSEgoKdmlvbGF0aW9ucxgCIAMoCSKzAQoGVGlsZU9wEigKA2FkZBgBIAEoCzIZLmFpLmRhc2hib2FyZHMudjEuQWRkVGlsZUgAEi4KBnVwZGF0ZRgCIAEoCzIcLmFpLmRhc2hib2FyZHMudjEuVXBkYXRlVGlsZUgAEi4KBnJlbW92ZRgDIAEoCzIcLmFpLmRhc2hib2FyZHMudjEuUmVtb3ZlVGlsZUgAEhIKCnZpb2xhdGlvbnMYBCADKAlCCwoCb3ASBbpIAggBIkwKB0FkZFRpbGUSQQoEdGlsZRgBIAEoCzIrLmRhc2hib2FyZC5kYXNoYm9hcmRzLnYxLkRhc2hib2FyZFRpbGVJbnB1dEIGukgDyAEBImkKClVwZGF0ZVRpbGUSGAoHdGlsZV9pZBgBIAEoCUIHukgEcgIQARJBCgR0aWxlGAIgASgLMisuZGFzaGJvYXJkLmRhc2hib2FyZHMudjEuRGFzaGJvYXJkVGlsZUlucHV0Qga6SAPIAQEiJgoKUmVtb3ZlVGlsZRIYCgd0aWxlX2lkGAEgASgJQge6SARyAhABMmQKGURhc2hib2FyZEFzc2lzdGFudFNlcnZpY2USRwoEVHVybhIdLmFpLmRhc2hib2FyZHMudjEuVHVyblJlcXVlc3QaHi5haS5kYXNoYm9hcmRzLnYxLlR1cm5SZXNwb25zZTABQkpaSGdpdGh1Yi5jb20vcHVnLXNoL3B1Zy9pbnRlcm5hbC9nZW4vcHJvdG8vYWkvZGFzaGJvYXJkcy92MTthaWRhc2hib2FyZHN2MWIIZWRpdGlvbnNw6Ac", [file_buf_validate_validate, file_dashboard_dashboards_v1_dashboards]);

/**
 * @generated from message ai.dashboards.v1.TurnRequest
 */
export type TurnRequest = Message$1<"ai.dashboards.v1.TurnRequest"> & {
  /**
   * Identifies which persisted conversation this turn belongs to. The caller
   * mints one (e.g. per dashboard-builder session) and reuses it across turns.
   * Bounded and pattern-constrained because the value is the last segment of a
   * Redis key: a ":" here would blur the boundary with the caller scope in
   * front of it.
   *
   * @generated from field: string conversation_id = 1;
   */
  conversationId: string;

  /**
   * @generated from field: ai.dashboards.v1.ConversationState state = 2;
   */
  state?: ConversationState | undefined;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message ai.dashboards.v1.TurnRequest.
 * Use `create(TurnRequestSchema)` to create a new message.
 */
export const TurnRequestSchema: GenMessage<TurnRequest> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 0);

/**
 * @generated from message ai.dashboards.v1.ConversationState
 */
export type ConversationState = Message$1<"ai.dashboards.v1.ConversationState"> & {
  /**
   * The draft the operations apply to. Reuses Dashboard so it is the same
   * message the webapp's draft state already holds and buildUpsertRequest
   * already consumes. This is still client-supplied every turn — message
   * history is not; it is persisted server-side, scoped to the caller.
   *
   * Not validated: the draft may legitimately hold a tile that fails
   * DashboardTile rules — the flagged TileOp the assistant itself emitted, which
   * the user is now asking it to fix. The server only reads the draft.
   *
   * @generated from field: dashboard.dashboards.v1.Dashboard draft = 1;
   */
  draft?: Dashboard | undefined;
};

/**
 * Describes the message ai.dashboards.v1.ConversationState.
 * Use `create(ConversationStateSchema)` to create a new message.
 */
export const ConversationStateSchema: GenMessage<ConversationState> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 1);

/**
 * @generated from message ai.dashboards.v1.Message
 */
export type Message = Message$1<"ai.dashboards.v1.Message"> & {
  /**
   * @generated from field: ai.dashboards.v1.Message.Role role = 1;
   */
  role: Message_Role;

  /**
   * @generated from field: string content = 2;
   */
  content: string;
};

/**
 * Describes the message ai.dashboards.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 2);

/**
 * @generated from enum ai.dashboards.v1.Message.Role
 */
export enum Message_Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROLE_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: ROLE_ASSISTANT = 2;
   */
  ASSISTANT = 2,
}

/**
 * Describes the enum ai.dashboards.v1.Message.Role.
 */
export const Message_RoleSchema: GenEnum<Message_Role> = /*@__PURE__*/
  enumDesc(file_ai_dashboards_v1_assistant, 2, 0);

/**
 * @generated from message ai.dashboards.v1.TurnResponse
 */
export type TurnResponse = Message$1<"ai.dashboards.v1.TurnResponse"> & {
  /**
   * @generated from oneof ai.dashboards.v1.TurnResponse.chunk
   */
  chunk: {
    /**
     * Assistant prose, streamed incrementally.
     *
     * @generated from field: string text = 1;
     */
    value: string;
    case: "text";
  } | {
    /**
     * One operation. Validated against the tile's own protovalidate rules — but
     * see TileOp.violations: a tile the assistant could not make valid is still
     * emitted, flagged, so the user can correct it by hand.
     *
     * @generated from field: ai.dashboards.v1.TileOp op = 2;
     */
    value: TileOp;
    case: "op";
  } | {
    /**
     * @generated from field: ai.dashboards.v1.TurnDone done = 3;
     */
    value: TurnDone;
    case: "done";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message ai.dashboards.v1.TurnResponse.
 * Use `create(TurnResponseSchema)` to create a new message.
 */
export const TurnResponseSchema: GenMessage<TurnResponse> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 3);

/**
 * @generated from message ai.dashboards.v1.TurnDone
 */
export type TurnDone = Message$1<"ai.dashboards.v1.TurnDone"> & {
  /**
   * Tiles the assistant abandoned without producing an op at all. A tile that
   * merely failed validation is emitted as a flagged TileOp instead, so in
   * practice this carries only assistant-side faults (e.g. a misconfigured
   * validator, where flagging would mean shipping a tile nothing ever checked).
   * Empty on a clean turn; clients should surface it as an error, not as a
   * correctable draft.
   *
   * @generated from field: repeated ai.dashboards.v1.FailedOp failed = 1;
   */
  failed: FailedOp[];
};

/**
 * Describes the message ai.dashboards.v1.TurnDone.
 * Use `create(TurnDoneSchema)` to create a new message.
 */
export const TurnDoneSchema: GenMessage<TurnDone> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 4);

/**
 * @generated from message ai.dashboards.v1.FailedOp
 */
export type FailedOp = Message$1<"ai.dashboards.v1.FailedOp"> & {
  /**
   * @generated from field: string intent = 1;
   */
  intent: string;

  /**
   * @generated from field: repeated string violations = 2;
   */
  violations: string[];
};

/**
 * Describes the message ai.dashboards.v1.FailedOp.
 * Use `create(FailedOpSchema)` to create a new message.
 */
export const FailedOpSchema: GenMessage<FailedOp> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 5);

/**
 * TileOp is a single edit to the draft. Operations rather than a whole-draft
 * rewrite: a tile the model never mentions is untouched by construction, so
 * silence can never delete. DashboardsService.Upsert deletes tiles absent from
 * its request, which makes that distinction load-bearing.
 *
 * @generated from message ai.dashboards.v1.TileOp
 */
export type TileOp = Message$1<"ai.dashboards.v1.TileOp"> & {
  /**
   * @generated from oneof ai.dashboards.v1.TileOp.op
   */
  op: {
    /**
     * @generated from field: ai.dashboards.v1.AddTile add = 1;
     */
    value: AddTile;
    case: "add";
  } | {
    /**
     * @generated from field: ai.dashboards.v1.UpdateTile update = 2;
     */
    value: UpdateTile;
    case: "update";
  } | {
    /**
     * @generated from field: ai.dashboards.v1.RemoveTile remove = 3;
     */
    value: RemoveTile;
    case: "remove";
  } | { case: undefined; value?: undefined };

  /**
   * Non-empty when the assistant could not make this tile valid within its
   * repair budget and is surfacing it for manual correction. The strings are
   * the protovalidate violation messages verbatim — already human-readable
   * prose, suitable to show the user.
   *
   * A flagged tile is deliberately NOT save-safe: DashboardsService.Upsert runs
   * the same rules server-side and will reject it. Clients must render it as a
   * must-fix draft state and block save until it validates. An op with no
   * violations passed validation and can be saved normally.
   *
   * @generated from field: repeated string violations = 4;
   */
  violations: string[];
};

/**
 * Describes the message ai.dashboards.v1.TileOp.
 * Use `create(TileOpSchema)` to create a new message.
 */
export const TileOpSchema: GenMessage<TileOp> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 6);

/**
 * @generated from message ai.dashboards.v1.AddTile
 */
export type AddTile = Message$1<"ai.dashboards.v1.AddTile"> & {
  /**
   * @generated from field: dashboard.dashboards.v1.DashboardTileInput tile = 1;
   */
  tile?: DashboardTileInput | undefined;
};

/**
 * Describes the message ai.dashboards.v1.AddTile.
 * Use `create(AddTileSchema)` to create a new message.
 */
export const AddTileSchema: GenMessage<AddTile> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 7);

/**
 * UpdateTile replaces the whole tile rather than carrying a field mask: the
 * model receives the current tile in context and returns the updated one, which
 * is markedly easier for a language model to get right. The blast radius is one
 * tile either way.
 *
 * @generated from message ai.dashboards.v1.UpdateTile
 */
export type UpdateTile = Message$1<"ai.dashboards.v1.UpdateTile"> & {
  /**
   * @generated from field: string tile_id = 1;
   */
  tileId: string;

  /**
   * @generated from field: dashboard.dashboards.v1.DashboardTileInput tile = 2;
   */
  tile?: DashboardTileInput | undefined;
};

/**
 * Describes the message ai.dashboards.v1.UpdateTile.
 * Use `create(UpdateTileSchema)` to create a new message.
 */
export const UpdateTileSchema: GenMessage<UpdateTile> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 8);

/**
 * @generated from message ai.dashboards.v1.RemoveTile
 */
export type RemoveTile = Message$1<"ai.dashboards.v1.RemoveTile"> & {
  /**
   * @generated from field: string tile_id = 1;
   */
  tileId: string;
};

/**
 * Describes the message ai.dashboards.v1.RemoveTile.
 * Use `create(RemoveTileSchema)` to create a new message.
 */
export const RemoveTileSchema: GenMessage<RemoveTile> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 9);

/**
 * DashboardAssistantService turns a conversation into validated edits to a
 * dashboard draft. Message history is persisted server-side, scoped to the
 * authenticated caller; only the draft round-trips through the client each turn.
 *
 * The service is implemented by the ai role in this repo (internal/app/ai +
 * internal/core/assistant) and calls back into shared.insights.v1 with the
 * caller's forwarded JWT, so its reads are authorized exactly as the user's own.
 *
 * @generated from service ai.dashboards.v1.DashboardAssistantService
 */
export const DashboardAssistantService: GenService<{
  /**
   * Turn processes one user message against the current draft and streams back
   * assistant prose plus zero or more validated tile operations.
   *
   * @generated from rpc ai.dashboards.v1.DashboardAssistantService.Turn
   */
  turn: {
    methodKind: "server_streaming";
    input: typeof TurnRequestSchema;
    output: typeof TurnResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ai_dashboards_v1_assistant, 0);

