// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ai/dashboards/v1/assistant.proto (package ai.dashboards.v1, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Dashboard, DashboardTileInput } from "../../../dashboard/dashboards/v1/dashboards_pb";
import { file_dashboard_dashboards_v1_dashboards } from "../../../dashboard/dashboards/v1/dashboards_pb";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file ai/dashboards/v1/assistant.proto.
 */
export const file_ai_dashboards_v1_assistant: GenFile = /*@__PURE__*/
  fileDesc("CiBhaS9kYXNoYm9hcmRzL3YxL2Fzc2lzdGFudC5wcm90bxIQYWkuZGFzaGJvYXJkcy52MSJeCgtUdXJuUmVxdWVzdBIyCgVzdGF0ZRgBIAEoCzIjLmFpLmRhc2hib2FyZHMudjEuQ29udmVyc2F0aW9uU3RhdGUSGwoHbWVzc2FnZRgCIAEoCUIKukgHcgUQARiQTiJ+ChFDb252ZXJzYXRpb25TdGF0ZRI2CghtZXNzYWdlcxgBIAMoCzIZLmFpLmRhc2hib2FyZHMudjEuTWVzc2FnZUIJukgGkgEDEMgBEjEKBWRyYWZ0GAIgASgLMiIuZGFzaGJvYXJkLmRhc2hib2FyZHMudjEuRGFzaGJvYXJkIpUBCgdNZXNzYWdlEjgKBHJvbGUYASABKA4yHi5haS5kYXNoYm9hcmRzLnYxLk1lc3NhZ2UuUm9sZUIKukgHggEEEAEgABIPCgdjb250ZW50GAIgASgJIj8KBFJvbGUSFAoQUk9MRV9VTlNQRUNJRklFRBAAEg0KCVJPTEVfVVNFUhABEhIKDlJPTEVfQVNTSVNUQU5UEAIiewoMVHVyblJlc3BvbnNlEg4KBHRleHQYASABKAlIABImCgJvcBgCIAEoCzIYLmFpLmRhc2hib2FyZHMudjEuVGlsZU9wSAASKgoEZG9uZRgDIAEoCzIaLmFpLmRhc2hib2FyZHMudjEuVHVybkRvbmVIAEIHCgVjaHVuayI2CghUdXJuRG9uZRIqCgZmYWlsZWQYASADKAsyGi5haS5kYXNoYm9hcmRzLnYxLkZhaWxlZE9wIi4KCEZhaWxlZE9wEg4KBmludGVudBgBIAEoCRISCgp2aW9sYXRpb25zGAIgAygJIrMBCgZUaWxlT3ASKAoDYWRkGAEgASgLMhkuYWkuZGFzaGJvYXJkcy52MS5BZGRUaWxlSAASLgoGdXBkYXRlGAIgASgLMhwuYWkuZGFzaGJvYXJkcy52MS5VcGRhdGVUaWxlSAASLgoGcmVtb3ZlGAMgASgLMhwuYWkuZGFzaGJvYXJkcy52MS5SZW1vdmVUaWxlSAASEgoKdmlvbGF0aW9ucxgEIAMoCUILCgJvcBIFukgCCAEiTAoHQWRkVGlsZRJBCgR0aWxlGAEgASgLMisuZGFzaGJvYXJkLmRhc2hib2FyZHMudjEuRGFzaGJvYXJkVGlsZUlucHV0Qga6SAPIAQEiaQoKVXBkYXRlVGlsZRIYCgd0aWxlX2lkGAEgASgJQge6SARyAhABEkEKBHRpbGUYAiABKAsyKy5kYXNoYm9hcmQuZGFzaGJvYXJkcy52MS5EYXNoYm9hcmRUaWxlSW5wdXRCBrpIA8gBASImCgpSZW1vdmVUaWxlEhgKB3RpbGVfaWQYASABKAlCB7pIBHICEAEyZAoZRGFzaGJvYXJkQXNzaXN0YW50U2VydmljZRJHCgRUdXJuEh0uYWkuZGFzaGJvYXJkcy52MS5UdXJuUmVxdWVzdBoeLmFpLmRhc2hib2FyZHMudjEuVHVyblJlc3BvbnNlMAFCSlpIZ2l0aHViLmNvbS9wdWctc2gvcHVnL2ludGVybmFsL2dlbi9wcm90by9haS9kYXNoYm9hcmRzL3YxO2FpZGFzaGJvYXJkc3YxYghlZGl0aW9uc3DoBw", [file_buf_validate_validate, file_dashboard_dashboards_v1_dashboards]);

/**
 * @generated from message ai.dashboards.v1.TurnRequest
 */
export type TurnRequest = Message$1<"ai.dashboards.v1.TurnRequest"> & {
  /**
   * @generated from field: ai.dashboards.v1.ConversationState state = 1;
   */
  state?: ConversationState | undefined;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message ai.dashboards.v1.TurnRequest.
 * Use `create(TurnRequestSchema)` to create a new message.
 */
export const TurnRequestSchema: GenMessage<TurnRequest> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 0);

/**
 * @generated from message ai.dashboards.v1.ConversationState
 */
export type ConversationState = Message$1<"ai.dashboards.v1.ConversationState"> & {
  /**
   * @generated from field: repeated ai.dashboards.v1.Message messages = 1;
   */
  messages: Message[];

  /**
   * The draft the operations apply to. Reuses Dashboard so it is the same
   * message the webapp's draft state already holds and buildUpsertRequest
   * already consumes.
   *
   * @generated from field: dashboard.dashboards.v1.Dashboard draft = 2;
   */
  draft?: Dashboard | undefined;
};

/**
 * Describes the message ai.dashboards.v1.ConversationState.
 * Use `create(ConversationStateSchema)` to create a new message.
 */
export const ConversationStateSchema: GenMessage<ConversationState> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 1);

/**
 * @generated from message ai.dashboards.v1.Message
 */
export type Message = Message$1<"ai.dashboards.v1.Message"> & {
  /**
   * @generated from field: ai.dashboards.v1.Message.Role role = 1;
   */
  role: Message_Role;

  /**
   * @generated from field: string content = 2;
   */
  content: string;
};

/**
 * Describes the message ai.dashboards.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 2);

/**
 * @generated from enum ai.dashboards.v1.Message.Role
 */
export enum Message_Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROLE_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: ROLE_ASSISTANT = 2;
   */
  ASSISTANT = 2,
}

/**
 * Describes the enum ai.dashboards.v1.Message.Role.
 */
export const Message_RoleSchema: GenEnum<Message_Role> = /*@__PURE__*/
  enumDesc(file_ai_dashboards_v1_assistant, 2, 0);

/**
 * @generated from message ai.dashboards.v1.TurnResponse
 */
export type TurnResponse = Message$1<"ai.dashboards.v1.TurnResponse"> & {
  /**
   * @generated from oneof ai.dashboards.v1.TurnResponse.chunk
   */
  chunk: {
    /**
     * Assistant prose, streamed incrementally.
     *
     * @generated from field: string text = 1;
     */
    value: string;
    case: "text";
  } | {
    /**
     * One operation. Validated against the tile's own protovalidate rules — but
     * see TileOp.violations: a tile the assistant could not make valid is still
     * emitted, flagged, so the user can correct it by hand.
     *
     * @generated from field: ai.dashboards.v1.TileOp op = 2;
     */
    value: TileOp;
    case: "op";
  } | {
    /**
     * @generated from field: ai.dashboards.v1.TurnDone done = 3;
     */
    value: TurnDone;
    case: "done";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message ai.dashboards.v1.TurnResponse.
 * Use `create(TurnResponseSchema)` to create a new message.
 */
export const TurnResponseSchema: GenMessage<TurnResponse> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 3);

/**
 * @generated from message ai.dashboards.v1.TurnDone
 */
export type TurnDone = Message$1<"ai.dashboards.v1.TurnDone"> & {
  /**
   * Tiles the assistant abandoned without producing an op at all. A tile that
   * merely failed validation is emitted as a flagged TileOp instead, so in
   * practice this carries only assistant-side faults (e.g. a misconfigured
   * validator, where flagging would mean shipping a tile nothing ever checked).
   * Empty on a clean turn; clients should surface it as an error, not as a
   * correctable draft.
   *
   * @generated from field: repeated ai.dashboards.v1.FailedOp failed = 1;
   */
  failed: FailedOp[];
};

/**
 * Describes the message ai.dashboards.v1.TurnDone.
 * Use `create(TurnDoneSchema)` to create a new message.
 */
export const TurnDoneSchema: GenMessage<TurnDone> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 4);

/**
 * @generated from message ai.dashboards.v1.FailedOp
 */
export type FailedOp = Message$1<"ai.dashboards.v1.FailedOp"> & {
  /**
   * @generated from field: string intent = 1;
   */
  intent: string;

  /**
   * @generated from field: repeated string violations = 2;
   */
  violations: string[];
};

/**
 * Describes the message ai.dashboards.v1.FailedOp.
 * Use `create(FailedOpSchema)` to create a new message.
 */
export const FailedOpSchema: GenMessage<FailedOp> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 5);

/**
 * TileOp is a single edit to the draft. Operations rather than a whole-draft
 * rewrite: a tile the model never mentions is untouched by construction, so
 * silence can never delete. DashboardsService.Upsert deletes tiles absent from
 * its request, which makes that distinction load-bearing.
 *
 * @generated from message ai.dashboards.v1.TileOp
 */
export type TileOp = Message$1<"ai.dashboards.v1.TileOp"> & {
  /**
   * @generated from oneof ai.dashboards.v1.TileOp.op
   */
  op: {
    /**
     * @generated from field: ai.dashboards.v1.AddTile add = 1;
     */
    value: AddTile;
    case: "add";
  } | {
    /**
     * @generated from field: ai.dashboards.v1.UpdateTile update = 2;
     */
    value: UpdateTile;
    case: "update";
  } | {
    /**
     * @generated from field: ai.dashboards.v1.RemoveTile remove = 3;
     */
    value: RemoveTile;
    case: "remove";
  } | { case: undefined; value?: undefined };

  /**
   * Non-empty when the assistant could not make this tile valid within its
   * repair budget and is surfacing it for manual correction. The strings are
   * the protovalidate violation messages verbatim — already human-readable
   * prose, suitable to show the user.
   *
   * A flagged tile is deliberately NOT save-safe: DashboardsService.Upsert runs
   * the same rules server-side and will reject it. Clients must render it as a
   * must-fix draft state and block save until it validates. An op with no
   * violations passed validation and can be saved normally.
   *
   * @generated from field: repeated string violations = 4;
   */
  violations: string[];
};

/**
 * Describes the message ai.dashboards.v1.TileOp.
 * Use `create(TileOpSchema)` to create a new message.
 */
export const TileOpSchema: GenMessage<TileOp> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 6);

/**
 * @generated from message ai.dashboards.v1.AddTile
 */
export type AddTile = Message$1<"ai.dashboards.v1.AddTile"> & {
  /**
   * @generated from field: dashboard.dashboards.v1.DashboardTileInput tile = 1;
   */
  tile?: DashboardTileInput | undefined;
};

/**
 * Describes the message ai.dashboards.v1.AddTile.
 * Use `create(AddTileSchema)` to create a new message.
 */
export const AddTileSchema: GenMessage<AddTile> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 7);

/**
 * UpdateTile replaces the whole tile rather than carrying a field mask: the
 * model receives the current tile in context and returns the updated one, which
 * is markedly easier for a language model to get right. The blast radius is one
 * tile either way.
 *
 * @generated from message ai.dashboards.v1.UpdateTile
 */
export type UpdateTile = Message$1<"ai.dashboards.v1.UpdateTile"> & {
  /**
   * @generated from field: string tile_id = 1;
   */
  tileId: string;

  /**
   * @generated from field: dashboard.dashboards.v1.DashboardTileInput tile = 2;
   */
  tile?: DashboardTileInput | undefined;
};

/**
 * Describes the message ai.dashboards.v1.UpdateTile.
 * Use `create(UpdateTileSchema)` to create a new message.
 */
export const UpdateTileSchema: GenMessage<UpdateTile> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 8);

/**
 * @generated from message ai.dashboards.v1.RemoveTile
 */
export type RemoveTile = Message$1<"ai.dashboards.v1.RemoveTile"> & {
  /**
   * @generated from field: string tile_id = 1;
   */
  tileId: string;
};

/**
 * Describes the message ai.dashboards.v1.RemoveTile.
 * Use `create(RemoveTileSchema)` to create a new message.
 */
export const RemoveTileSchema: GenMessage<RemoveTile> = /*@__PURE__*/
  messageDesc(file_ai_dashboards_v1_assistant, 9);

/**
 * DashboardAssistantService turns a conversation into validated edits to a
 * dashboard draft. It is stateless: the client owns the draft and the history,
 * and both round-trip through ConversationState on every turn.
 *
 * The service is implemented outside this repo (es/pug-sh/ai) and calls back
 * into shared.insights.v1 with the caller's forwarded JWT, so its reads are
 * authorized exactly as the user's own.
 *
 * @generated from service ai.dashboards.v1.DashboardAssistantService
 */
export const DashboardAssistantService: GenService<{
  /**
   * Turn processes one user message against the current draft and streams back
   * assistant prose plus zero or more validated tile operations.
   *
   * @generated from rpc ai.dashboards.v1.DashboardAssistantService.Turn
   */
  turn: {
    methodKind: "server_streaming";
    input: typeof TurnRequestSchema;
    output: typeof TurnResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ai_dashboards_v1_assistant, 0);

