import { formatColor, parseColor } from '../lib/color/parse'
import { BUILTIN_IDS, BUILTINS, type BuiltinId } from './builtin'
import { compileVariant } from './compile'
import { PUG_AUTH_SURFACE } from './presets/pug'
import { POLARITIES, type Polarity } from './tokens'

// The built-in themes as CSS, written to src/theme/generated/builtin-themes.css by
// `bun run generate:themes` and imported from index.css, so built-ins ride the same pipeline the
// tokens always have. Installed themes never come through here — they're applied as inline
// variables at runtime.

const selectorFor = (id: BuiltinId, polarity: Polarity) => {
  const dark = polarity === 'dark' ? '.dark' : ''
  return id === 'pug' ? `:root${dark}` : `:root${dark}[data-theme="${id}"]`
}

const declarations = (vars: Record<string, string>) =>
  Object.entries(vars)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n')

export const builtinThemesCss = () => {
  const blocks: string[] = []
  const pugVars = {} as Record<Polarity, Record<string, string>>
  for (const id of BUILTIN_IDS) {
    for (const polarity of POLARITIES) {
      const compiled = compileVariant({ id, builtin: true, family: BUILTINS[id], polarity })
      const problems = compiled.report.filter(i => i.severity === 'error' || !(i.rule === 'V2' && i.path === 'faint'))
      if (problems.length) {
        throw new Error(
          `built-in ${id} (${polarity}) fails validation:\n${problems.map(i => `  ${i.rule} ${i.message}`).join('\n')}`,
        )
      }
      if (id === 'pug') pugVars[polarity] = compiled.vars
      blocks.push(`${selectorFor(id, polarity)} {\n${declarations(compiled.vars)}\n}`)
    }
  }

  // The sign-in pages stay on Pug whatever the root carries: a full reset, plus light's nine
  // re-solved tokens. `color` is re-anchored because elements inheriting it from body would
  // otherwise keep the outer theme's ink.
  const authLight = { ...pugVars.light }
  for (const [token, value] of Object.entries(PUG_AUTH_SURFACE)) {
    const parsed = parseColor(value as string)
    if (!parsed) throw new Error(`PUG_AUTH_SURFACE.${token} is not a colour`)
    authLight[`--${token}`] = formatColor(parsed)
  }
  blocks.push(`.auth-surface {\n${declarations(authLight)}\n  color: var(--foreground);\n}`)
  blocks.push(`.dark .auth-surface {\n${declarations(pugVars.dark)}\n  color: var(--foreground);\n}`)

  const header = [
    '/* Generated by scripts/generate-themes.ts from src/theme/presets — do not edit.',
    '   Run `bun run generate:themes` after changing a preset; builtin-themes.test.ts fails while this is stale. */',
  ].join('\n')
  return `${header}\n\n${blocks.join('\n\n')}\n`
}
