// The registry's vocabulary: every themeable token, every event colour group, and the axes a theme
// varies on. Kept free of logic so the format, the registry and the schema generator can all import
// it without pulling each other in.

export const TOKENS = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'link',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'faint',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
  'success',
  'warning',
  'positive',
  'caution',
  'negative',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
  'sidebar',
  'sidebar-foreground',
  'sidebar-primary',
  'sidebar-primary-foreground',
  'sidebar-accent',
  'sidebar-accent-foreground',
  'sidebar-border',
  'sidebar-ring',
  'chart-background',
  'chart-foreground',
  'chart-foreground-muted',
  'chart-label',
  'chart-line-primary',
  'chart-line-secondary',
  'chart-crosshair',
  'chart-grid',
  'chart-brush-border',
  'chart-tooltip-background',
  'chart-tooltip-foreground',
  'chart-tooltip-muted',
  'chart-marker-background',
  'chart-marker-border',
  'chart-marker-foreground',
  'chart-scale-01',
  'chart-scale-02',
  'chart-scale-03',
  'chart-scale-04',
  'chart-scale-05',
  'chart-scale-pattern-color',
  'heat-1',
  'heat-2',
  'heat-3',
  'heat-4',
  'heat-5',
  'heat-6',
  'heat-7',
  'heat-ink-dark',
  'heat-ink-light',
  'heat-1-ink',
  'heat-2-ink',
  'heat-3-ink',
  'heat-4-ink',
  'heat-5-ink',
  'heat-6-ink',
  'heat-7-ink',
  'identity-surface',
  'identity-ink',
  'syntax-keyword',
  'syntax-string',
  'syntax-class',
] as const

export type TokenName = (typeof TOKENS)[number]

export const isTokenName = (name: string): name is TokenName => (TOKENS as readonly string[]).includes(name)

export const GROUPS = [
  'navigation',
  'interaction',
  'lifecycle',
  'auth',
  'commerce',
  'discovery',
  'forms',
  'media',
  'notifications',
  'chat',
  'billing',
  'support',
  'workspace',
  'invitations',
  'files',
  'integrations',
  'api',
  'sharing',
  'failure',
  'success',
] as const

export type GroupName = (typeof GROUPS)[number]

export const isGroupName = (name: string): name is GroupName => (GROUPS as readonly string[]).includes(name)

export type Polarity = 'light' | 'dark'
export type Contrast = 'standard' | 'high'
export const POLARITIES: Polarity[] = ['light', 'dark']
