// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dashboard/customers/v1/customers.proto (package dashboard.customers.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dashboard/customers/v1/customers.proto.
 */
export const file_dashboard_customers_v1_customers: GenFile = /*@__PURE__*/
  fileDesc("CiZkYXNoYm9hcmQvY3VzdG9tZXJzL3YxL2N1c3RvbWVycy5wcm90bxIWZGFzaGJvYXJkLmN1c3RvbWVycy52MSIOCgxHZXRNZVJlcXVlc3QiSwoNR2V0TWVSZXNwb25zZRITCgtjdXN0b21lcl9pZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIWCg5lbWFpbF92ZXJpZmllZBgDIAEoCCIyChJTZXRQYXNzd29yZFJlcXVlc3QSHAoIcGFzc3dvcmQYASABKAlCCrpIB8gBAXICKEgiFQoTU2V0UGFzc3dvcmRSZXNwb25zZTLUAQoQQ3VzdG9tZXJzU2VydmljZRJWCgVHZXRNZRIkLmRhc2hib2FyZC5jdXN0b21lcnMudjEuR2V0TWVSZXF1ZXN0GiUuZGFzaGJvYXJkLmN1c3RvbWVycy52MS5HZXRNZVJlc3BvbnNlIgASaAoLU2V0UGFzc3dvcmQSKi5kYXNoYm9hcmQuY3VzdG9tZXJzLnYxLlNldFBhc3N3b3JkUmVxdWVzdBorLmRhc2hib2FyZC5jdXN0b21lcnMudjEuU2V0UGFzc3dvcmRSZXNwb25zZSIAQk1aS2dpdGh1Yi5jb20vcHVnLXNoL3B1Zy9pbnRlcm5hbC9nZW4vcHJvdG8vZGFzaGJvYXJkL2N1c3RvbWVycy92MTtjdXN0b21lcnN2MWIIZWRpdGlvbnNw6Ac", [file_buf_validate_validate]);

/**
 * @generated from message dashboard.customers.v1.GetMeRequest
 */
export type GetMeRequest = Message<"dashboard.customers.v1.GetMeRequest"> & {
};

/**
 * Describes the message dashboard.customers.v1.GetMeRequest.
 * Use `create(GetMeRequestSchema)` to create a new message.
 */
export const GetMeRequestSchema: GenMessage<GetMeRequest> = /*@__PURE__*/
  messageDesc(file_dashboard_customers_v1_customers, 0);

/**
 * @generated from message dashboard.customers.v1.GetMeResponse
 */
export type GetMeResponse = Message<"dashboard.customers.v1.GetMeResponse"> & {
  /**
   * @generated from field: string customer_id = 1;
   */
  customerId: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: bool email_verified = 3;
   */
  emailVerified: boolean;
};

/**
 * Describes the message dashboard.customers.v1.GetMeResponse.
 * Use `create(GetMeResponseSchema)` to create a new message.
 */
export const GetMeResponseSchema: GenMessage<GetMeResponse> = /*@__PURE__*/
  messageDesc(file_dashboard_customers_v1_customers, 1);

/**
 * @generated from message dashboard.customers.v1.SetPasswordRequest
 */
export type SetPasswordRequest = Message<"dashboard.customers.v1.SetPasswordRequest"> & {
  /**
   * @generated from field: string password = 1;
   */
  password: string;
};

/**
 * Describes the message dashboard.customers.v1.SetPasswordRequest.
 * Use `create(SetPasswordRequestSchema)` to create a new message.
 */
export const SetPasswordRequestSchema: GenMessage<SetPasswordRequest> = /*@__PURE__*/
  messageDesc(file_dashboard_customers_v1_customers, 2);

/**
 * @generated from message dashboard.customers.v1.SetPasswordResponse
 */
export type SetPasswordResponse = Message<"dashboard.customers.v1.SetPasswordResponse"> & {
};

/**
 * Describes the message dashboard.customers.v1.SetPasswordResponse.
 * Use `create(SetPasswordResponseSchema)` to create a new message.
 */
export const SetPasswordResponseSchema: GenMessage<SetPasswordResponse> = /*@__PURE__*/
  messageDesc(file_dashboard_customers_v1_customers, 3);

/**
 * CustomersService exposes the authenticated caller's own account. JWT-only
 * (dashboard) — it never reveals any other customer's data.
 *
 * @generated from service dashboard.customers.v1.CustomersService
 */
export const CustomersService: GenService<{
  /**
   * GetMe returns the calling customer's id, email, and verification status.
   *
   * @generated from rpc dashboard.customers.v1.CustomersService.GetMe
   */
  getMe: {
    methodKind: "unary";
    input: typeof GetMeRequestSchema;
    output: typeof GetMeResponseSchema;
  },
  /**
   * @generated from rpc dashboard.customers.v1.CustomersService.SetPassword
   */
  setPassword: {
    methodKind: "unary";
    input: typeof SetPasswordRequestSchema;
    output: typeof SetPasswordResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dashboard_customers_v1_customers, 0);

