// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file sdk/events/v1/events.proto (package sdk.events.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { PropertyValue } from "../../../common/v1/property_value_pb";
import { file_common_v1_property_value } from "../../../common/v1/property_value_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sdk/events/v1/events.proto.
 */
export const file_sdk_events_v1_events: GenFile = /*@__PURE__*/
  fileDesc("ChpzZGsvZXZlbnRzL3YxL2V2ZW50cy5wcm90bxINc2RrLmV2ZW50cy52MSJFChJCYXRjaENyZWF0ZVJlcXVlc3QSLwoGZXZlbnRzGAEgAygLMhQuc2RrLmV2ZW50cy52MS5FdmVudEIJukgGkgEDEOgHIicKE0JhdGNoQ3JlYXRlUmVzcG9uc2USEAoIYWNjZXB0ZWQYASABKA0ikAcKBUV2ZW50Eh0KCGV2ZW50X2lkGAEgASgJQgu6SAjIAQFyA7ABARJBCg9hdXRvX3Byb3BlcnRpZXMYAiADKAsyKC5zZGsuZXZlbnRzLnYxLkV2ZW50LkF1dG9Qcm9wZXJ0aWVzRW50cnkSRQoRY3VzdG9tX3Byb3BlcnRpZXMYAyADKAsyKi5zZGsuZXZlbnRzLnYxLkV2ZW50LkN1c3RvbVByb3BlcnRpZXNFbnRyeRIbCgtkaXN0aW5jdF9pZBgEIAEoCUIGukgDyAEBEhQKBGtpbmQYBSABKAlCBrpIA8gBARI2CgpvY2N1cl90aW1lGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIGukgDyAEBEh8KCnNlc3Npb25faWQYByABKAlCC7pICMgBAXIDsAEBGk8KE0F1dG9Qcm9wZXJ0aWVzRW50cnkSCwoDa2V5GAEgASgJEicKBXZhbHVlGAIgASgLMhguY29tbW9uLnYxLlByb3BlcnR5VmFsdWU6AjgBGlEKFUN1c3RvbVByb3BlcnRpZXNFbnRyeRILCgNrZXkYASABKAkSJwoFdmFsdWUYAiABKAsyGC5jb21tb24udjEuUHJvcGVydHlWYWx1ZToCOAE6rQO6SKkDGm4KHWV2ZW50LmtpbmRfbm9fcmVzZXJ2ZWRfcHJlZml4Ei5ldmVudCBraW5kIG11c3Qgbm90IHVzZSByZXNlcnZlZCBwcmVmaXggJ3B1Zy4nGh0hdGhpcy5raW5kLnN0YXJ0c1dpdGgoJ3B1Zy4nKRqDAQojZXZlbnQuYXV0b19wcm9wZXJ0aWVzX2RvbGxhcl9wcmVmaXgSKGF1dG9fcHJvcGVydGllcyBrZXlzIG11c3Qgc3RhcnQgd2l0aCAnJCcaMnRoaXMuYXV0b19wcm9wZXJ0aWVzLmFsbChrZXksIGtleS5zdGFydHNXaXRoKCckJykpGrABCihldmVudC5jdXN0b21fcHJvcGVydGllc19ub19kb2xsYXJfcHJlZml4Ek1jdXN0b21fcHJvcGVydGllcyBrZXlzIG11c3Qgbm90IHN0YXJ0IHdpdGggJyQnIChyZXNlcnZlZCBmb3IgYXV0by1wcm9wZXJ0aWVzKRo1dGhpcy5jdXN0b21fcHJvcGVydGllcy5hbGwoa2V5LCAha2V5LnN0YXJ0c1dpdGgoJyQnKSkiUgoKRXZlbnRCYXRjaBIkCgZldmVudHMYASADKAsyFC5zZGsuZXZlbnRzLnYxLkV2ZW50Eh4KCnByb2plY3RfaWQYAiABKAlCCrpIB8gBAXICEAEyZQoNRXZlbnRzU2VydmljZRJUCgtCYXRjaENyZWF0ZRIhLnNkay5ldmVudHMudjEuQmF0Y2hDcmVhdGVSZXF1ZXN0GiIuc2RrLmV2ZW50cy52MS5CYXRjaENyZWF0ZVJlc3BvbnNlQkFaP2dpdGh1Yi5jb20vcHVnLXNoL3B1Zy9pbnRlcm5hbC9nZW4vcHJvdG8vc2RrL2V2ZW50cy92MTtldmVudHN2MWIIZWRpdGlvbnNw6Ac", [file_buf_validate_validate, file_common_v1_property_value, file_google_protobuf_timestamp]);

/**
 * @generated from message sdk.events.v1.BatchCreateRequest
 */
export type BatchCreateRequest = Message<"sdk.events.v1.BatchCreateRequest"> & {
  /**
   * @generated from field: repeated sdk.events.v1.Event events = 1;
   */
  events: Event[];
};

/**
 * Describes the message sdk.events.v1.BatchCreateRequest.
 * Use `create(BatchCreateRequestSchema)` to create a new message.
 */
export const BatchCreateRequestSchema: GenMessage<BatchCreateRequest> = /*@__PURE__*/
  messageDesc(file_sdk_events_v1_events, 0);

/**
 * @generated from message sdk.events.v1.BatchCreateResponse
 */
export type BatchCreateResponse = Message<"sdk.events.v1.BatchCreateResponse"> & {
  /**
   * @generated from field: uint32 accepted = 1;
   */
  accepted: number;
};

/**
 * Describes the message sdk.events.v1.BatchCreateResponse.
 * Use `create(BatchCreateResponseSchema)` to create a new message.
 */
export const BatchCreateResponseSchema: GenMessage<BatchCreateResponse> = /*@__PURE__*/
  messageDesc(file_sdk_events_v1_events, 1);

/**
 * @generated from message sdk.events.v1.Event
 */
export type Event = Message<"sdk.events.v1.Event"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * @generated from field: map<string, common.v1.PropertyValue> auto_properties = 2;
   */
  autoProperties: { [key: string]: PropertyValue };

  /**
   * @generated from field: map<string, common.v1.PropertyValue> custom_properties = 3;
   */
  customProperties: { [key: string]: PropertyValue };

  /**
   * @generated from field: string distinct_id = 4;
   */
  distinctId: string;

  /**
   * @generated from field: string kind = 5;
   */
  kind: string;

  /**
   * @generated from field: google.protobuf.Timestamp occur_time = 6;
   */
  occurTime?: Timestamp;

  /**
   * @generated from field: string session_id = 7;
   */
  sessionId: string;
};

/**
 * Describes the message sdk.events.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_sdk_events_v1_events, 2);

/**
 * @generated from message sdk.events.v1.EventBatch
 */
export type EventBatch = Message<"sdk.events.v1.EventBatch"> & {
  /**
   * @generated from field: repeated sdk.events.v1.Event events = 1;
   */
  events: Event[];

  /**
   * @generated from field: string project_id = 2;
   */
  projectId: string;
};

/**
 * Describes the message sdk.events.v1.EventBatch.
 * Use `create(EventBatchSchema)` to create a new message.
 */
export const EventBatchSchema: GenMessage<EventBatch> = /*@__PURE__*/
  messageDesc(file_sdk_events_v1_events, 3);

/**
 * @generated from service sdk.events.v1.EventsService
 */
export const EventsService: GenService<{
  /**
   * @generated from rpc sdk.events.v1.EventsService.BatchCreate
   */
  batchCreate: {
    methodKind: "unary";
    input: typeof BatchCreateRequestSchema;
    output: typeof BatchCreateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sdk_events_v1_events, 0);

